words = [
    "astro",
    "astrojs",
    "bitbucket",
    "braintree",
    "cloudflare",
    "cloudflarestorage",
    "cwd",
    "dompurify",
    "fflate",
    "gitlab",
    "iconify",
    "jsdocs",
    "jsdom",
    "pathe",
    "pino",
    "preact",
    "prerender",
    "rollup",
    "runed",
    "shiki",
    "unplugin",
    "vercel",
    "vite",
    "vitest",
    "zod",
]
